### ISSUE TITLE
[NEOS-1284] Update TS-Build Job to have Nextjs caching

### ISSUE THREAD

**Issue by nickzelei** [nucleuscloud/neosync#2380]
```

  build:
    name: TS Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm
          cache-dependency-path: ./frontend/package-lock.json

      - run: npm install
      - name: Build
        run: npm run build
        env:
          NODE_ENV: production
```

Should add this:

```
uses: actions/cache@v4
with:
  # See here for caching with `yarn` https://github.com/actions/cache/blob/main/examples.md#node---yarn or you can leverage caching with actions/setup-node https://github.com/actions/setup-node
  path: |
    ~~/.npm
    ${{ github.workspace }}/.next/cache
  # Generate a new cache whenever packages or source files change.
  key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
  # If source files changed but packages didn't, rebuild from a prior cache.
  restore-keys: |
    ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
```

Although we don't need the `~~/.npm` I don't think because the node action does that for us automatically.

<sub>From [SyncLinear.com](https://synclinear.com) | [NEOS-1284](https://linear.app/nucleus-cloud/issue/NEOS-1284/update-ts-build-job-to-have-nextjs-caching)</sub>
